const express=require('express');
const cors=require('cors');
const app=express();
app.use(cors());
app.use(express.json());
let tasks=[];
app.get('/tasks',(req,res)=>res.json(tasks));
app.post('/tasks',(req,res)=>{const t={id:Date.now(),title:req.body.title,status:'Pending',dueDate:req.body.dueDate};tasks.push(t);res.json(t)});
app.put('/tasks/:id',(req,res)=>{const id=parseInt(req.params.id);tasks=tasks.map(t=>t.id===id?{...t,...req.body}:t);res.json({message:'updated'})});
app.delete('/tasks/:id',(req,res)=>{const id=parseInt(req.params.id);tasks=tasks.filter(t=>t.id!==id);res.json({message:'deleted'})});
app.listen(5000,()=>console.log('Server running on port 5000'));
